/*package com.rfg.tprm.questionnaire.model;


import java.util.Date;


public class QsttQuestionBranch  implements java.io.Serializable {


     private QsttQuestionBranchId id;
     private QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
     private QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
     private Long ansOptionId;
     private boolean isSkip;
     private boolean isMandatory;
//     private String tagName;
     private Date createDate;
     private Long createBy;
     private Date updateDate;
     private Long updateBy;
     private Long DQuestionnaireId;

    public QsttQuestionBranch() {
    }

	
    public QsttQuestionBranch(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2, boolean isSkip, boolean isMandatory) {
        this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
        this.isSkip = isSkip;
        this.isMandatory = isMandatory;
    }
//    public QsttQuestionBranch(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2, QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1, Long ansOptionId, boolean isSkip, boolean isMandatory, String tagName, Date createDate, Long createBy, Date updateDate, Long updateBy, Long DQuestionnaireId) {
//       this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
//       this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
//       this.ansOptionId = ansOptionId;
//       this.isSkip = isSkip;
//       this.isMandatory = isMandatory;
//       this.tagName = tagName;
//       this.createDate = createDate;
//       this.createBy = createBy;
//       this.updateDate = updateDate;
//       this.updateBy = updateBy;
//       this.DQuestionnaireId = DQuestionnaireId;
//    }
   
    public QsttQuestionBranchId getId() {
        return this.id;
    }
    
    public void setId(QsttQuestionBranchId id) {
        this.id = id;
    }
    public QsttQuestionMap getQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2() {
        return this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
    }
    
    public void setQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2) {
        this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
    }
    public QsttQuestionMap getQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1() {
        return this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
    }
    
    public void setQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1) {
        this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
    }
    public Long getAnsOptionId() {
        return this.ansOptionId;
    }
    
    public void setAnsOptionId(Long ansOptionId) {
        this.ansOptionId = ansOptionId;
    }
    public boolean isIsSkip() {
        return this.isSkip;
    }
    
    public void setIsSkip(boolean isSkip) {
        this.isSkip = isSkip;
    }
    public boolean isIsMandatory() {
        return this.isMandatory;
    }
    
    public void setIsMandatory(boolean isMandatory) {
        this.isMandatory = isMandatory;
    }
//    public String getTagName() {
//        return this.tagName;
//    }
//    
//    public void setTagName(String tagName) {
//        this.tagName = tagName;
//    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Long getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Long getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
    public Long getDQuestionnaireId() {
        return this.DQuestionnaireId;
    }
    
    public void setDQuestionnaireId(Long DQuestionnaireId) {
        this.DQuestionnaireId = DQuestionnaireId;
    }




}*/


package com.moe.sls.model;
// Generated Sep 10, 2014 2:38:51 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * QsttQuestionBranch generated by hbm2java
 */
public class QsttQuestionBranch  implements java.io.Serializable {


     private QsttQuestionBranchId id;
     private QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
     private QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
     private Long ansOptionId;
     private boolean isSkip;
     private boolean isMandatory;
     private String tagName;
     private Date createDate;
     private Long createBy;
     private Date updateDate;
     private Long updateBy;
     private Long DQuestionnaireId;

    public QsttQuestionBranch() {
    }

	
    public QsttQuestionBranch(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2, boolean isSkip, boolean isMandatory) {
        this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
        this.isSkip = isSkip;
        this.isMandatory = isMandatory;
    }
    public QsttQuestionBranch(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2, QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1, Long ansOptionId, boolean isSkip, boolean isMandatory, String tagName, Date createDate, Long createBy, Date updateDate, Long updateBy, Long DQuestionnaireId) {
       this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
       this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
       this.ansOptionId = ansOptionId;
       this.isSkip = isSkip;
       this.isMandatory = isMandatory;
       this.tagName = tagName;
       this.createDate = createDate;
       this.createBy = createBy;
       this.updateDate = updateDate;
       this.updateBy = updateBy;
       this.DQuestionnaireId = DQuestionnaireId;
    }
   
    public QsttQuestionBranchId getId() {
        return this.id;
    }
    
    public void setId(QsttQuestionBranchId id) {
        this.id = id;
    }
    public QsttQuestionMap getQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2() {
        return this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
    }
    
    public void setQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2) {
        this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk2;
    }
    public QsttQuestionMap getQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1() {
        return this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
    }
    
    public void setQsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1(QsttQuestionMap qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1) {
        this.qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1 = qsttQuestionMapByQsttQuestionBranchQsttQuestionMapFk1;
    }
    public Long getAnsOptionId() {
        return this.ansOptionId;
    }
    
    public void setAnsOptionId(Long ansOptionId) {
        this.ansOptionId = ansOptionId;
    }
    public boolean isIsSkip() {
        return this.isSkip;
    }
    
    public void setIsSkip(boolean isSkip) {
        this.isSkip = isSkip;
    }
    public boolean isIsMandatory() {
        return this.isMandatory;
    }
    
    public void setIsMandatory(boolean isMandatory) {
        this.isMandatory = isMandatory;
    }
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Long getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Long getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
    public Long getDQuestionnaireId() {
        return this.DQuestionnaireId;
    }
    
    public void setDQuestionnaireId(Long DQuestionnaireId) {
        this.DQuestionnaireId = DQuestionnaireId;
    }




}





