/*package com.rfg.tprm.questionnaire.model;



public class QsttQuestionBranchId  implements java.io.Serializable {


     private long questionId;
     private long qsttQuestionnaireDefId;

    public QsttQuestionBranchId() {
    }

    public QsttQuestionBranchId(long questionId, long qsttQuestionnaireDefId) {
       this.questionId = questionId;
       this.qsttQuestionnaireDefId = qsttQuestionnaireDefId;
    }
   
    public long getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(long questionId) {
        this.questionId = questionId;
    }
    public long getQsttQuestionnaireDefId() {
        return this.qsttQuestionnaireDefId;
    }
    
    public void setQsttQuestionnaireDefId(long qsttQuestionnaireDefId) {
        this.qsttQuestionnaireDefId = qsttQuestionnaireDefId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QsttQuestionBranchId) ) return false;
		 QsttQuestionBranchId castOther = ( QsttQuestionBranchId ) other; 
         
		 return (this.getQuestionId()==castOther.getQuestionId())
 && (this.getQsttQuestionnaireDefId()==castOther.getQsttQuestionnaireDefId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getQuestionId();
         result = 37 * result + (int) this.getQsttQuestionnaireDefId();
         return result;
   }   


} */


package com.moe.sls.model;
// Generated Sep 10, 2014 2:38:51 PM by Hibernate Tools 3.6.0



/**
 * QsttQuestionBranchId generated by hbm2java
 */
public class QsttQuestionBranchId  implements java.io.Serializable {


     private long questionId;
     private long qsttQuestionnaireDefId;

    public QsttQuestionBranchId() {
    }

    public QsttQuestionBranchId(long questionId, long qsttQuestionnaireDefId) {
       this.questionId = questionId;
       this.qsttQuestionnaireDefId = qsttQuestionnaireDefId;
    }
   
    public long getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(long questionId) {
        this.questionId = questionId;
    }
    public long getQsttQuestionnaireDefId() {
        return this.qsttQuestionnaireDefId;
    }
    
    public void setQsttQuestionnaireDefId(long qsttQuestionnaireDefId) {
        this.qsttQuestionnaireDefId = qsttQuestionnaireDefId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QsttQuestionBranchId) ) return false;
		 QsttQuestionBranchId castOther = ( QsttQuestionBranchId ) other; 
         
		 return (this.getQuestionId()==castOther.getQuestionId())
 && (this.getQsttQuestionnaireDefId()==castOther.getQsttQuestionnaireDefId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getQuestionId();
         result = 37 * result + (int) this.getQsttQuestionnaireDefId();
         return result;
   }   


}





